---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "fusion-jupyter.fullname" . }}-pvc"
spec:
  accessModes:
    {{ .Values.storage.accessModes | toYaml | nindent 4 }}
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: {{ .Values.storage.requests | quote }}
{{ if .Values.storage.storageClassName }}
  storageClassName: "{{ .Values.storage.storageClassName }}"
{{ end }}
