apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusion-jupyter.name" . }}
  labels:
    app.kubernetes.io/target-image-tag: {{ .Values.image.tag }}
{{ include "fusion-jupyter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fusion-jupyter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
