---

apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: {{ include "fusion.devops-ui.fullname" .  }}
  labels:
{{ include "fusion.devops-ui.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "devops-ui"
      app.kubernetes.io/part-of: "fusion"
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
