{{- if .Values.components.proxy }}
{{- $tlsEnabled := or .Values.proxy.tls.enabled ( eq (include "fusion.tls.enabled" .) "true" ) -}}

{{- if $tlsEnabled }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}"
rules:
- apiGroups: [ "cert-manager.io" ]
  resources: [ "certificates" ]
  verbs: [ "get", "create", "delete" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get" ]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}-acct"
  apiGroup: ""
roleRef:
  kind: Role
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}"
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}-acct"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.proxy.component }}
{{- end }}
