# deploy zookeeper only when `components.zookeeper` is true
{{- if .Values.components.zookeeper }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.zookeeper.component }}
  annotations:
{{ toYaml .Values.zookeeper.service.annotations | indent 4 }}
spec:
  ports:
    - name: follower
      port: {{ .Values.zookeeper.ports.follower }}
    - name: leader-election
      port: {{ .Values.zookeeper.ports.leaderElection }}
    - name: client
      port: {{ .Values.zookeeper.ports.client }}
    {{- if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
    - name: client-tls
      port: {{ .Values.zookeeper.ports.clientTls }}
    {{- end }}
  clusterIP: None
  selector:
    {{- include "pulsar.matchLabels" . | nindent 4 }}
    component: {{ .Values.zookeeper.component }}
{{- end }}
