---

apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "{{ template "fusion.sql-service.fullname" . }}"
  labels:
    {{ include "fusion.sql-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "sql-service"
      app.kubernetes.io/part-of: "fusion"
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
