{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "fusion.fusion-admin.fullname" .  }}
  labels:
    {{ include "fusion.fusion-admin.labels" . | nindent 4 }}
spec:
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "fusion-admin-tls-secret"
{{ end }}
  rules:
  - host: admin-{{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "fusion.fusion-admin.serviceName" .  }}
          servicePort: {{ .Values.service.externalPort }}
        path: /
{{- end -}}
