{{- if .Values.server.enabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.singleNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
{{- if .Values.controller.persistence }}
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  {{- if .Values.controller.persistence.postgresql }}
  - {{ .Values.controller.persistence.postgresql.userNameSecret.name }}
  - {{ .Values.controller.persistence.postgresql.passwordSecret.name }}
  {{- end}}
  {{- if .Values.controller.persistence.mysql }}
  - {{ .Values.controller.persistence.mysql.userNameSecret.name }}
  - {{ .Values.controller.persistence.mysql.passwordSecret.name }}
  {{- end}}
  verbs:
  - get
{{- end}}
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - cronworkflows
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
{{- if not .Values.singleNamespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.name }}-cluster-template
rules:
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  verbs:
  - get
  - list
  - watch
  {{- if .Values.server.clusterWorkflowTemplates.enableEditing }}
  - create
  - update
  - patch
  - delete
  {{- end }}
{{- end -}}
{{- end -}}
{{- end }}
