{{- if or .Values.components.proxy .Values.extra.proxy }}
{{- if .Values.proxy.pdb.usePolicy }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.proxy.component }}
spec:
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
      component: {{ .Values.proxy.component }}
  {{- if .Values.proxy.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.proxy.pdb.maxUnavailable }}
  {{- else if .Values.proxy.pdb.minAvailable }}
  minAvailable: {{ .Values.proxy.pdb.minAvailable }}
  {{- end }}
{{- end }}
{{- end }}
