{{- if .Values.rbac.create }}
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
{{- if $tlsEnabled }}

---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "fusion.fusion-log-forwarder.fullname" . }}"

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "fusion.fusion-log-forwarder.fullname" . }}"
rules:
- apiGroups: [ "cert-manager.io" ]
  resources: [ "certificates" ]
  verbs: [ "get", "create", "delete" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get" ]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "fusion.fusion-log-forwarder.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ include "fusion.fusion-log-forwarder.fullname" . }}"
  apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "fusion.fusion-log-forwarder.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- end }}
{{- end }}
