apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "connector-plugins.fusion.lucidworks.com"
spec:
  group: "fusion.lucidworks.com"
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
  scope: "Namespaced"
  names:
    plural: "connector-plugins"
    singular: "connector-plugin"
    kind: "ConnectorPlugin"
    categories:
      - connectors
  validation:
    openAPIV3Schema:
      required: [ "spec" ]
      properties:
        spec:
          required: [ "type", "id", "version" ]
          properties:
            type:
              type: "string"
              minimum: 1
            id:
              type: "string"
              minimum: 1
            version:
              type: "string"
              minimum: 1
            imageName:
              type: "string"
              minimum: 1
            imageTag:
              type: "string"
              minimum: 1
            md5:
              type: "string"
              minimum: 1
            connectorSDKVersion:
              type: "string"
              minimum: 1
            usePluginSpecificImage:
              type: "boolean"
              minimum: 1
            replicas:
              type: "integer"
              minimum: 1